In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# loading the data
from sklearn.datasets import load_breast_cancer
cancer_Data = load_breast_cancer()
cancer_Data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
print(cancer_Data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [3]:
cancer_Data['data']

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], shape=(569, 30))

In [4]:
cancer_Data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [5]:
df_features = pd.DataFrame(cancer_Data['data'], columns=cancer_Data['feature_names'])

In [ ]:
df_features.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64

In [6]:
cancer_Data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
cancer_Data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [9]:
df_Target = pd.DataFrame(cancer_Data['target'], columns=['is_malignant_cancer'])
df_Target.tail(20)

is_malignant_cancer
549                    1
550                    1
551                    1
552                    1
553                    1
554                    1
555                    1
556                    1
557                    1
558                    1
559                    1
560                    1
561                    1
562                    0
563                    0
564                    0
565                    0
566                    0
567                    0
568                    1

In [26]:
X = df_features
y = df_Target.values.ravel()

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [12]:
from sklearn.svm import SVC

In [ ]:
model = SVC()
model.fit(X_train, y_train)


c:\Users\Hp\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [14]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0])

In [15]:
# model evaluation
from sklearn.metrics import classification_report, accuracy_score
print("Model accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Model accuracy: 0.9210526315789473
              precision    recall  f1-score   support

           0       0.94      0.82      0.87        38
           1       0.91      0.97      0.94        76

    accuracy                           0.92       114
   macro avg       0.93      0.89      0.91       114
weighted avg       0.92      0.92      0.92       114



# OPTIMIZING THE MODEL
1. Kernel
2. C

# RUN VSM with"linear","C=10"

In [16]:
from sklearn.metrics import accuracy_score

linear_svc = SVC(kernel='poly', C=10)
linear_svc.fit(X_train, y_train)

y_pred_linear = linear_svc.predict(X_test)

print("Linear model accuracy:", accuracy_score(y_test, y_pred_linear))

Linear model accuracy: 0.9298245614035088


c:\Users\Hp\OneDrive\Desktop\Machine_Learning\.venv\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [17]:
linear_svc.score(X_train, y_train)


0.9186813186813186

In [18]:
linear_svc.score(X_test, y_test)

0.9298245614035088

In [28]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1, 1, 2, 3, 4, 6, 10, 100],
               'kernel': ['linear', 'rbf', 'poly']}
opt_model= GridSearchCV(SVC(), param_grid)
opt_model.fit(X_train, y_train)
y_opt_pred = opt_model.predict(X_test)

In [30]:
opt_model.best_params_

{'C': 3, 'kernel': 'linear'}

In [32]:
opt_model.score(X_train, y_train)

0.9736263736263736

In [33]:
opt_model.score(X_test, y_test)

0.956140350877193

In [49]:
query= df_features.loc[100:100, :]
query

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
100        13.61         24.98           88.05      582.7          0.09488   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
100           0.08511         0.08625              0.04489         0.1609   

     mean fractal dimension  ...  worst radius  worst texture  \
100                 0.05871  ...         16.99          35.27   

     worst perimeter  worst area  worst smoothness  worst compactness  \
100            108.6       906.5            0.1265             0.1943   

     worst concavity  worst concave points  worst symmetry  \
100           0.3169                0.1184          0.2651   

     worst fractal dimension  
100                  0.07397  

[1 rows x 30 columns]

In [ ]:
result= opt_model.predict(query)

if result==1:
    print("The person has malignant cancer")
else:
    print("The person has belign malignant cancer")

The person does not have malignant cancer


In [51]:
df_Target.iloc[100]

is_malignant_cancer    0
Name: 100, dtype: int64